### ISSUE TITLE
mingw32 - using geotiff problems

### ISSUE THREAD

**Issue by Rasbats** [Rasbats/photolayer_pi#21]
Trying to get the dependencies correct. Tries to use local libs for geotiff and libtiff but this fails. 

[https://app.circleci.com/pipelines/github/Rasbats/photolayer_pi/302/workflows/9bb4df9d-eb70-4580-b45d-08731862a26d/jobs/3030](url)

Tried to add mingw32-libtiff and mingw32-geotiff to opencpn-deps.spec but this does not work. Still tries to use the local libs.

**Comment by Rasbats** [comment]
Should 'leamas' appear when building the script?

`# Create the  fedora build script

cat > build.sh << "EOF"
su -c "dnf install -q -y sudo dnf-plugins-core"
sudo dnf -y copr enable leamas/opencpn-mingw
sudo dnf -q builddep  -y /project/mingw/fedora/opencpn-deps.spec
cd /project
rm -rf build; mkdir build; cd build
cmake \
    -DCMAKE_BUILD_TYPE=Release \
    -DCMAKE_TOOLCHAIN_FILE=../mingw/fedora/toolchain.cmake \
    ..
make -j $(nproc) VERBOSE=1 tarball
EOF`

**Comment by Rasbats** [comment]
Alec... you commented out mingw in .circleci/config.yml when you fixed the flatpak build. I uncommented as part of my attempts to fix the issue.
# Missing libtiff and libgeotiff dependencies

**Comment by leamas** [comment]
It's not possible to build because of missing deps, not packaged for mingw. There is a long-term solution based on rebuilding these deps from sources (already done in the flatpak build).  For now, I suggest that you comment mingw out again and also add a link to this issue. And then closes this issue, basically as  WONTFIX

We can live with plugins which cannot be built for mingw due to dependencies. It's definitely not an important platform (I can say that, I initiated it once upon a time...)

The missing mingw dependencies are libgeotiff and proj.

**Comment by Rasbats** [comment]
Thanks Alec... I will go with this. Photolayer is now good to go. I will get this plugin updated in the catalog.

**Comment by leamas** [comment]
> I will get this plugin updated in the catalog.

Right. 

I'm a bit curious about the git-push things, which updates your plugins clone. Do you use it? Does it work?

**Comment by Rasbats** [comment]
I cause myself some confusion because I use github desktop as well as the git cmd. It does all work and I now have photolayer in the catalog again and working with focal.

The only issue is that after the pull request is merged by Dave my fork is 1 commit ahead. To sync my fork with the upstream master do you have some git ideas, using the command line from my clone?

**Comment by leamas** [comment]
yup.

You need to define two remotes, The first is origin, and is probably ok. Check it using ` git remote show origin`. It should show the ssh url to you repo, "git@github.com:Rasbats/plugins.git"

If you havn't already done it, then add a new remote called upstream using `git remote add upstream https://github.com/OpenCPN/plugins.git`. That is, *upstream* is Dave's repo, the one you cloned. Since it's a http url it is basically read-only access to this.


With this in place, google "git rebase" and try to understand what's it all about. Really, do it, you'll need it sooner or later.
Then, the thing we do all the time:

    $ git checkout master
    $ git rebase upstream/master

This will sync your repo with Dave's. There are three possible outcomes:

  1. It just works (it should, in this case)
  1. There are conflicts  you need to resolve. Google should have told you what it means
  1. The whole thing is a mess with conflicts you can't resolve. In this case `git rebase --abort` takes you back to the starting point

You shouldn't be too worried, this will just work as long as no one else has changed "your"  plugins. Better safe than sorry, though.

**Comment by leamas** [comment]
hm... I might have missed something here:

  - If Dave's upstream repo is ahead of yours you need to rebase, see above
  - If your repo is ahead of upstream the only way to sync it is to make a new PR

**Comment by Rasbats** [comment]
Good... This is what I was missing:
If Dave's repo is ahead...
* $ git checkout master
* $ git rebase upstream/master
Because Dave's commit of the pull request has put the main repo one commit ahead of my fork.

This is what I have in the wiki:

* $ git checkout auto
* $ git rebase master
* $ git checkout master
* $ git merge --squash auto

I think this needs expanding a bit.

**Comment by leamas** [comment]
> Because Dave's commit of the pull request has put the main repo one commit ahead of my fork.

If I understand this correctly this happened because you made a PR from the auto branch (?). After all, when Dave merges the PR the upstream repo  is at identical to the branch you used for the PR. The situation then is what it is because the auto branch was one commit ahead of your master..

> I think this needs expanding a bit.

In what sense? More commands and/or more explaining text?

In general, the auto branch contains the last changes you have made.  If you follow the recipe in the wiki the state of the master branch will be exactly the same as the branch auto. That is, if you do `git diff master auto` it won't return anything at all, they are identical. 

If you then make a PR from the master branch and Dave merges it, the upstream master will be the same as your master. You can verify this using:

    $ git remote update upstream
    $ git diff master upstream/master
    $ git diff auto upstream/master

which will show that the state of all three branches are identical  (unless Dave merges a new PR)

Helicopter workflow view:

  - The _auto_ branch  is updated automagically when you build (i.e., by ci/git-push).
  - The wiki recipe updates your _master_ branch to the same state as the _auto_, merging the history to a single commit.
  - The _master_ branch is used to make a PR against upstream
  - When the PR is merged, _upstream/master_ is identical to the local _master_ (and thus also local _auto_)

**Comment by leamas** [comment]
Ah... I forgot: There will be a last commit in the master branch ahead of your branch. This is because Dace doesn't rebase the PRs, he merges them (like you do with my PRs). Yoy don't need to worry about this, the auto branch is automatically rebased and you will be fine after merging it next time.

**Comment by Rasbats** [comment]
The light is coming on! A bit dim but getting there. 

At the moment I am working with TideFinder, a Beta plugin. Ok, I make a tag which includes the text beta. I think the problem is that the build uses a clone of 'master' not 'Beta'. The end result is that when I try to --squash auto I am trying to put all those files that were taken from 'master' into the 'Beta'. Is this correct?

Is this why when I try the following I get conflicts:

* $ git checkout auto
* $ git rebase Beta

**Comment by leamas** [comment]
hm... also on thin ice here, bear with me. But: Assuming "the build" to be ci/git-push this is only concerned about the auto branch, nothing else.

But once upon a time, the auto branch was created as an offspring of master (?). And that might be the culprit.  Not tested, but I think working with the beta branch could be setup using something like this:'

    $ git branch -D auto    (drop the auto branch completely)
    $ git remote update upstream   (Better safe than sorry)
    $ git checkout -b auto upstream/beta   (Create a new auto branch based on Beta)
    $ git push origin auto:auto

... and then run a new build. You will now have auto branch based on upstream/Beta, and this should be simple to rebase using `git rebase upstream/Beta`. After which you can do a PR against the Beta branch. You should not have to repeat this as long as you work on the Beta branch, just rebase and make PRs as usual

**Comment by Rasbats** [comment]
Very nice solution. Thanks, this is now tested. I think I need to take up juggling. Hope the snow got cleared ok.

**Comment by leamas** [comment]
Yes, I got rid of it. Problem is that when I wake up tomorrow I'll  have to clear about the same amount again before I go to work.  Sigh.

Glad that it worked for you.
